### ISSUE TITLE
Cannot copy code to my Windows Computer

### ISSUE THREAD

**Issue by mvences** [akshatgui/Sequence_Editor#1]
I am now starting to check the various tools and code updates that arrived in July. For this Sequence Editor prototype, I have the problem that some of the files apparently are named in a way not accepted by Windows, as the filenames contain colons, such as in 
"itaxo.jpeg:Zone.Identifer"
I could just remove or rename these files in a Linux environment, but I am not sure how this will affect the performance of the code. Can you please rename these files and avoid special characters in filenames in the future, and make sure all works well with the renamed files? I will then proceed with checking the tool.

**Comment by akshatcx** [comment]
Hello, I have removed the `Zone.Identifer` files. You should be now able to run it in the Windows environment. These files are temporary files and should not have been in the repo. 

Let us know if there are any other issues.
